### ISSUE TITLE
Cached entities fetched with ngrx-data-pagination are dirty

### ISSUE THREAD

**Issue by Xartrick** [maxbendick/ngrx-data-pagination#5]
# The bug

If an entity is fetched using `ngrx-data-pagination`, we are unable to delete the entity using an `EntityCollectionService`.

# Why?

We are using `upsertManyInCache` to add entities to cache after we fetched them ([here](https://github.com/maxbendick/ngrx-data-pagination/blob/master/projects/ngrx-data-pagination/src/lib/pagination/store-interfaces/ngrx/pagination.ts#L37)). This method dispatch an `UPSERT_MANY` action catched [here](https://github.com/ngrx/platform/blob/0e9c4f4a20ca92a71ee331889109c7861708725f/modules/data/src/reducers/entity-collection-reducer-methods.ts#L1053). Entities saved to cache by this method are considered dirty and not saved to the remote storage behind the `DataService` by the [`EntityChangeTracker`](https://ngrx.io/guide/data/entity-change-tracker)

When trying to delete an entity, [`persist`](https://github.com/ngrx/platform/blob/b146af546a6ec54a26bac8b9c4c9db1356ebb4fd/modules/data/src/effects/entity-effects.ts#L77) method is called. But no call is made to our `DataService` because [`action.payload.skip`](https://ngrx.io/guide/data/entity-actions#entityactionskip) is `true`.

# Solution
We must reset changes of cached entities.

We may be able to dispatch a `SAVE_UPSERT_MANY_SUCCESS` (or maybe `SAVE_ENTITIES_SUCCESS`) action to reset `changeType` for entities in the `changeState` state.

**Comment by maxbendick** [comment]
Thanks for the great writeup! Repeating what you said to make sure I understand: you're saying the problem is that deleting an item through an `EntityCollectionService` doesn't call the delete endpoint as expected when the item was loaded through `ngrx-data-pagination`.

I believe your solution to dispatch a custom `SAVE_UPSERT_MANY_SUCCESS` action would work well :+1:

Another solution I have in mind would be to manually dispatch a `UPSERT_MANY` action with `action.payload.skip = false` instead of calling `upsertManyInCache` (assuming I understand correctly)

Again, thanks for the great writeup and digging into this problem! 🤩 Things are a little less hectic now for me, so I can implement a solution tomorrow, but you can implement it if you would rather.

**Comment by Xartrick** [comment]
You understood it right!

Dispatching an `UPSERT_MANY` action would make a request to the API to save those results. This is not something we want as we freshly fetched them. We know they are up to date. Also, we can't manually set `skip` value as it is overwritten by `@ngrx/data` internals (I already tried this using `this.dataService.delete('id', { skip: false })`).

I've created a [StackBlitz example](https://stackblitz.com/edit/angular-94ex4u?file=src%2Fapp%2Fcomponents%2Fapp.component.ts) of the issue so you can better understand it if you missed some piece of information.

**Comment by Xartrick** [comment]
I've created a [StackBlitz example](https://stackblitz.com/edit/angular-94ex4u?file=src%2Fapp%2Fcomponents%2Fapp.component.ts) of the issue so you can better understand it if you missed some piece of information.
